runtime: nodejs14
service: hackathon-server

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10
env_variables:
  DB_HOST: /cloudsql/team16-2021:us-central1:people
  DB_USERNAME: root
  DB_PASSWORD: Passw0rd
  DB_NAME: people
